import type { RequestHandler } from './$types';
import { aiRequest } from '$lib/server/ai-request';
import { buildDiagramDescription } from '$lib/utils/diagram-description';

const LANGUAGE_CONFIGS: Record<string, { name: string; ext: string; prompt: string }> = {
	'sql-mysql': {
		name: 'MySQL',
		ext: 'sql',
		prompt: 'Generate MySQL CREATE TABLE statements with proper data types (INT, VARCHAR, TEXT, DATETIME, DECIMAL, etc.), PRIMARY KEY, FOREIGN KEY constraints with ON DELETE/UPDATE, INDEX, AUTO_INCREMENT, ENGINE=InnoDB, DEFAULT CHARSET=utf8mb4.'
	},
	'sql-postgres': {
		name: 'PostgreSQL',
		ext: 'sql',
		prompt: 'Generate PostgreSQL CREATE TABLE statements with proper data types (SERIAL, INTEGER, VARCHAR, TEXT, TIMESTAMP, NUMERIC, etc.), PRIMARY KEY, FOREIGN KEY constraints with ON DELETE/UPDATE, indexes. Use SERIAL for auto-increment PKs.'
	},
	'sql-sqlite': {
		name: 'SQLite',
		ext: 'sql',
		prompt: 'Generate SQLite CREATE TABLE statements with proper data types (INTEGER, TEXT, REAL, BLOB), PRIMARY KEY (with AUTOINCREMENT where appropriate), FOREIGN KEY constraints. Include PRAGMA foreign_keys = ON at the top.'
	},
	'prisma': {
		name: 'Prisma Schema',
		ext: 'prisma',
		prompt: 'Generate a complete Prisma schema file. Include the generator and datasource blocks (use postgresql). Use proper Prisma types (@id, @default(autoincrement()), @relation, @unique, @map, etc.). Model names in PascalCase, field names in camelCase.'
	},
	'typeorm': {
		name: 'TypeORM',
		ext: 'ts',
		prompt: 'Generate TypeORM entity classes in TypeScript. Use decorators: @Entity(), @PrimaryGeneratedColumn(), @Column(), @ManyToOne(), @OneToMany(), @ManyToMany(), @JoinTable(), @JoinColumn(). Import from "typeorm". Use proper TypeScript types.'
	},
	'django': {
		name: 'Django Models',
		ext: 'py',
		prompt: 'Generate Django model classes in Python. Use models.Model as base. Use proper field types: CharField, IntegerField, TextField, DateTimeField, DecimalField, ForeignKey, ManyToManyField. Include Meta class, __str__ method, on_delete parameter.'
	},
	'laravel': {
		name: 'Laravel Migration',
		ext: 'php',
		prompt: 'Generate Laravel migration files. Use Schema::create with proper column types: $table->id(), $table->string(), $table->text(), $table->integer(), $table->timestamps(), $table->foreignId()->constrained(). Include both up() and down() methods.'
	},
	'sequelize': {
		name: 'Sequelize',
		ext: 'js',
		prompt: 'Generate Sequelize model definitions in JavaScript. Use DataTypes (STRING, INTEGER, TEXT, DATE, DECIMAL, BOOLEAN). Include associations (belongsTo, hasMany, belongsToMany). Use sequelize.define() syntax.'
	}
};

export const POST: RequestHandler = async ({ request, platform }) => {
	return aiRequest({
		request,
		platform,
		validateBody: (body) => {
			if (!Array.isArray(body.entities) || body.entities.length === 0) return false;
			if (!body.language || !LANGUAGE_CONFIGS[body.language]) return false;
			return true;
		},
		buildMessages: (body) => {
			const { entities, relationships, language } = body;
			const langConfig = LANGUAGE_CONFIGS[language];
			const diagramDesc = buildDiagramDescription(entities, relationships || []);

			const systemPrompt = `You are an expert software engineer. Convert the ER diagram below into production-ready code.

${langConfig.prompt}

Rules:
1. Generate ONLY the code — no markdown, no explanation, no comments saying "generated by AI"
2. Include helpful inline comments explaining relationships and constraints
3. Handle junction/bridge tables for M:N relationships
4. Use appropriate data types based on attribute names (e.g., "email" → VARCHAR(255), "price" → DECIMAL, "created_at" → DATETIME/TIMESTAMP)
5. Add proper indexes on foreign keys
6. Handle weak entities with composite keys if applicable
7. The code must be complete, runnable, and follow best practices for ${langConfig.name}
8. If attribute names are in Thai, keep them as-is in comments but use romanized/English versions for actual column/field names where needed
9. ALWAYS properly quote/escape all identifiers (table names, column names) using the target language's quoting mechanism`;

			return [
				{ role: 'system', content: systemPrompt },
				{ role: 'user', content: `Convert this ER diagram to ${langConfig.name} code:\n\n${diagramDesc}` }
			];
		},
		transformResponse: (text, body) => {
			const langConfig = LANGUAGE_CONFIGS[body.language];
			// Strip markdown code fences if present
			const code = text.replace(/^```[\w]*\n?/, '').replace(/\n?```$/, '').trim();
			return {
				code,
				language: langConfig.name,
				extension: langConfig.ext
			};
		},
		temperature: 0.2,
		maxTokens: 8192,
		jsonMode: false
	});
};
